name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment script
        env:
          API_KEY: ${{ secrets.API_KEY_WEATHER }}  
        run: |
          node deploy.js
